name: Docker Deploy

on:
  push:
    branches: [main, master]
    paths:
      - 'parser/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      parser-changed: ${{ steps.changes.outputs.parser }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            parser:
              - 'parser/**'

  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.parser-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./parser
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pharmacy-scraper:latest
            ghcr.io/${{ github.repository_owner }}/pharmacy-scraper:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 